### ISSUE TITLE
dyld_fatal_error: XCode 6.1 compiled code crashes on iPhone but not Simulator.

### ISSUE THREAD

**Issue by sebinsua** [owensd/json-swift#23]
I have a really weird bug.

JSON cannot be parsed by my iPhone 6 that runs iOS 8.1. It parses fine with the iPhone 6 Simulator.

This is an example of the code that I am trying to execute:

``` Swift
func testParsingObject() {      
        let str = NSString(string: "{}")
        let data = str.dataUsingEncoding(NSUTF8StringEncoding)

        let json = JSON.parse(data!) // This line fails.
}

func testParsingNumber() {      
        let str = NSString(string: "{\"number\": 50}")
        let data = str.dataUsingEncoding(NSUTF8StringEncoding)

        let json = JSON.parse(data!) // This line fails.
}

func testParsingString() {      
        let str = NSString(string: "{\"string\":\"here is a string\"}")
        let data = str.dataUsingEncoding(NSUTF8StringEncoding)

        let json = JSON.parse(data!) // This line fails.
}
```

Here is the kind of error crash that I am seeing (I just checked and it happens irrelevant of the data I pass in):

```
#0  0x0000000120009088 in dyld_fatal_error ()
#1  0x000000012000be48 in dyld::halt(char const*) ()
#2  0x000000012000bf18 in dyld::fastBindLazySymbol(ImageLoader**, unsigned long) ()
#3  0x0000000197ba5198 in dyld_stub_binder ()
#4  0x00000001007789c8 in JSONLib.JSValue.parseObject (JSONLib.JSValue.Type)<A : Swift.SequenceType>(JSONLib.ReplayableGenerator<A>) -> (value : Swift.Optional<JSONLib.JSValue>, error : Swift.Optional<JSONLib.Error>) ()
#5  0x0000000100777bfc in JSONLib.JSValue.parse (JSONLib.JSValue.Type)<A : Swift.SequenceType>(JSONLib.ReplayableGenerator<A>) -> (value : Swift.Optional<JSONLib.JSValue>, error : Swift.Optional<JSONLib.Error>) ()
#6  0x0000000100776578 in JSONLib.JSValue.parse (JSONLib.JSValue.Type)(Swift.UnsafeBufferPointer<Swift.UInt8>) -> (value : Swift.Optional<JSONLib.JSValue>, error : Swift.Optional<JSONLib.Error>) ()
#7  0x0000000100777a68 in JSONLib.JSValue.parse (JSONLib.JSValue.Type)(ObjectiveC.NSData) -> (value : Swift.Optional<JSONLib.JSValue>, error : Swift.Optional<JSONLib.Error>) ()
#8  0x000000010012ead8 in Spokes.AppDelegate.testParsingObject (Spokes.AppDelegate)() -> () at /Users/sebinsua/Development/Spokes/Spokes/AppDelegate.swift:40
```

I have hardcoded the data and am executing it from the AppDelegate to prove to myself that it's not related to any other logic I have in play and seems to be dependent on whether we've compiled for a device or not.

Any ideas? I'll come back if I work anything out myself.

**Comment by camill-a** [comment]
One solution for me was to Product > Clean project, under Xcode7
